### ISSUE TITLE
This is what the server returned: data: [DONE]

### ISSUE THREAD

**Issue by AtulRajVAASITS** [Zai-Kun/reverse-engineered-chatgpt#46]
Enter your prompt: hi
Traceback (most recent call last):
  File "d:\Working on\ml\research\test.py", line 1031, in <module>
    for message in conversation.chat(prompt):
  File "d:\Working on\ml\research\research\Lib\site-packages\re_gpt\sync_chatgpt.py", line 142, in chat
    raise UnexpectedResponseError(error, server_response)
re_gpt.errors.UnexpectedResponseError: An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.
This is what the server returned: data: [DONE]

**Comment by AtulRajVAASITS** [comment]
i am using the newly cloned one

**Comment by Ojas1024** [comment]
Did you find a way out?

**Comment by AtulRajVAASITS** [comment]
no

**Comment by skyrank7700** [comment]
I think developer abandoned this project
